plugins:
  unikname_enabled:
    default: false
    client: true
  unikname_discovery_document:
    default: "https://integ.connect.unikname.com/oidc/.well-known/openid-configuration"
  unikname_client_id:
    default: ""
  unikname_client_secret:
    default: ""
  unikname_allow_association_change:
    default: false
  unikname_overrides_email:
    default: false
  unikname_authorize_scope:
    default: "openid"
  unikname_verbose_logging:
    default: false
  unikname_token_scope:
    default: ""
  unikname_error_redirects:
    default: ''
    type: list
    list_type: secret
  unikname_authorize_parameters:
    default: ''
    type: list
    list_type: compact
